require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "lib/tasks/*.rake"
    - "bin/*"
    - "config/puma.rb"
    - "config/spring.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
    - "spec/spec_helper.rb"
    - "spec/integration/**/*.rb"
Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 50