---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/registrations":
    post:
      summary: create a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - username
              - email
              - password
              - password_confirmation
  "/sessions":
    post:
      summary: Creates a user session
      tags:
      - Users Sessions
      parameters: []
      responses:
        '200':
          description: user session created
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/logout":
    delete:
      summary: Destroys a user session
      tags:
      - Users Sessions
      security:
      - BearerAuth: []
      responses:
        '204':
          description: user session destroyed
  "/users":
    get:
      summary: Retrieves a list of users
      tags:
      - Users
      security:
      - BearerAuth: []
      responses:
        '200':
          description: list of users retrieved
  "/users/{_username}":
    parameters:
    - name: _username
      in: path
      description: Username of the user
      required: true
      schema:
        type: string
    get:
      summary: Retrieves a user by username
      tags:
      - Users
      security:
      - BearerAuth: []
      responses:
        '200':
          description: user retrieved
        '404':
          description: user not found
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
